# 22張大阿爾克納牌 + 56張小阿爾克納牌
tarot_deck = [
  {"id": "MA_00_Fool", "position": "↑"},
  {"id": "MA_01_Magician", "position": "↑"},
  {"id": "MA_02_HighPriestess", "position": "↑"},
  {"id": "MA_03_Empress", "position": "↑"},
  {"id": "MA_04_Emperor", "position": "↑"},
  {"id": "MA_05_Hierophant", "position": "↑"},
  {"id": "MA_06_Lovers", "position": "↑"},
  {"id": "MA_07_Chariot", "position": "↑"},
  {"id": "MA_08_Strength", "position": "↑"},
  {"id": "MA_09_Hermit", "position": "↑"},
  {"id": "MA_10_WheelOfFortune", "position": "↑"},
  {"id": "MA_11_Justice", "position": "↑"},
  {"id": "MA_12_HangedMan", "position": "↑"},
  {"id": "MA_13_Death", "position": "↑"},
  {"id": "MA_14_Temperance", "position": "↑"},
  {"id": "MA_15_Devil", "position": "↑"},
  {"id": "MA_16_Tower", "position": "↑"},
  {"id": "MA_17_Star", "position": "↑"},
  {"id": "MA_18_Moon", "position": "↑"},
  {"id": "MA_19_Sun", "position": "↑"},
  {"id": "MA_20_Judgement", "position": "↑"},
  {"id": "MA_21_World", "position": "↑"},
  {"id": "MI_1_Ace of Wands", "position": "↑"},
  {"id": "MI_2_Two of Wands", "position": "↑"},
  {"id": "MI_3_Three of Wands", "position": "↑"},
  {"id": "MI_4_Four of Wands", "position": "↑"},
  {"id": "MI_5_Five of Wands", "position": "↑"},
  {"id": "MI_6_Six of Wands", "position": "↑"},
  {"id": "MI_7_Seven of Wands", "position": "↑"},
  {"id": "MI_8_Eight of Wands", "position": "↑"},
  {"id": "MI_9_Nine of Wands", "position": "↑"},
  {"id": "MI_10_Ten of Wands", "position": "↑"},
  {"id": "MI_Page_Page of Wands", "position": "↑"},
  {"id": "MI_Knight_Knight of Wands", "position": "↑"},
  {"id": "MI_Queen_Queen of Wands", "position": "↑"},
  {"id": "MI_King_King of Wands", "position": "↑"},
  {"id": "MI_1_Ace of Cups", "position": "↑"},
  {"id": "MI_2_Two of Cups", "position": "↑"},
  {"id": "MI_3_Three of Cups", "position": "↑"},
  {"id": "MI_4_Four of Cups", "position": "↑"},
  {"id": "MI_5_Five of Cups", "position": "↑"},
  {"id": "MI_6_Six of Cups", "position": "↑"},
  {"id": "MI_7_Seven of Cups", "position": "↑"},
  {"id": "MI_8_Eight of Cups", "position": "↑"},
  {"id": "MI_9_Nine of Cups", "position": "↑"},
  {"id": "MI_10_Ten of Cups", "position": "↑"},
  {"id": "MI_Page_Page of Cups", "position": "↑"},
  {"id": "MI_Knight_Knight of Cups", "position": "↑"},
  {"id": "MI_Queen_Queen of Cups", "position": "↑"},
  {"id": "MI_King_King of Cups", "position": "↑"},
  {"id": "MI_1_Ace of Swords", "position": "↑"},
  {"id": "MI_2_Two of Swords", "position": "↑"},
  {"id": "MI_3_Three of Swords", "position": "↑"},
  {"id": "MI_4_Four of Swords", "position": "↑"},
  {"id": "MI_5_Five of Swords", "position": "↑"},
  {"id": "MI_6_Six of Swords", "position": "↑"},
  {"id": "MI_7_Seven of Swords", "position": "↑"},
  {"id": "MI_8_Eight of Swords", "position": "↑"},
  {"id": "MI_9_Nine of Swords", "position": "↑"},
  {"id": "MI_10_Ten of Swords", "position": "↑"},
  {"id": "MI_Page_Page of Swords", "position": "↑"},
  {"id": "MI_Knight_Knight of Swords", "position": "↑"},
  {"id": "MI_Queen_Queen of Swords", "position": "↑"},
  {"id": "MI_King_King of Swords", "position": "↑"},
  {"id": "MI_1_Ace of Pentacles", "position": "↑"},
  {"id": "MI_2_Two of Pentacles", "position": "↑"},
  {"id": "MI_3_Three of Pentacles", "position": "↑"},
  {"id": "MI_4_Four of Pentacles", "position": "↑"},
  {"id": "MI_5_Five of Pentacles", "position": "↑"},
  {"id": "MI_6_Six of Pentacles", "position": "↑"},
  {"id": "MI_7_Seven of Pentacles", "position": "↑"},
  {"id": "MI_8_Eight of Pentacles", "position": "↑"},
  {"id": "MI_9_Nine of Pentacles", "position": "↑"},
  {"id": "MI_10_Ten of Pentacles", "position": "↑"},
  {"id": "MI_Page_Page of Pentacles", "position": "↑"},
  {"id": "MI_Knight_Knight of Pentacles", "position": "↑"},
  {"id": "MI_Queen_Queen of Pentacles", "position": "↑"},
  {"id": "MI_King_King of Pentacles", "position": "↑"}
]
