# 22張大阿爾克納牌
major_arcana = [
  "Ⅰ The Fool — 愚者",
  "Ⅱ The Magician — 魔術師",
  "Ⅲ The High Priestess — 女祭司",
  "Ⅳ The Empress — 皇后",
  "Ⅴ The Emperor — 皇帝",
  "Ⅵ The Hierophant — 教宗",
  "Ⅶ The Lovers — 戀人",
  "Ⅷ The Chariot — 戰車",
  "Ⅸ Strength — 力量",
  "Ⅹ The Hermit — 隱者",
  "Ⅺ Wheel of Fortune — 命運之輪",
  "Ⅻ Justice — 正義",
  "ⅩⅢ The Hanged Man — 吊人",
  "ⅩⅣ Death — 死神",
  "ⅩⅤ Temperance — 節制",
  "ⅩⅥ The Devil — 惡魔",
  "ⅩⅦ The Tower — 高塔",
  "ⅩⅧ The Star — 星星",
  "ⅩⅨ The Moon — 月亮",
  "ⅩⅩ The Sun — 太陽",
  "ⅩⅪ Judgement — 審判",
  "ⅩⅫ The World — 世界"
]

# 56張小阿爾克納牌
minor_arcana = [
  # Wands 權杖
  "Ace of Wands — 權杖一",
  "Two of Wands — 權杖二",
  "Three of Wands — 權杖三",
  "Four of Wands — 權杖四",
  "Five of Wands — 權杖五",
  "Six of Wands — 權杖六",
  "Seven of Wands — 權杖七",
  "Eight of Wands — 權杖八",
  "Nine of Wands — 權杖九",
  "Ten of Wands — 權杖十",
  "Page of Wands — 權杖侍者",
  "Knight of Wands — 權杖騎士",
  "Queen of Wands — 權杖皇后",
  "King of Wands — 權杖國王",

  # Cups 聖杯
  "Ace of Cups — 聖杯一",
  "Two of Cups — 聖杯二",
  "Three of Cups — 聖杯三",
  "Four of Cups — 聖杯四",
  "Five of Cups — 聖杯五",
  "Six of Cups — 聖杯六",
  "Seven of Cups — 聖杯七",
  "Eight of Cups — 聖杯八",
  "Nine of Cups — 聖杯九",
  "Ten of Cups — 聖杯十",
  "Page of Cups — 聖杯侍者",
  "Knight of Cups — 聖杯騎士",
  "Queen of Cups — 聖杯皇后",
  "King of Cups — 聖杯國王",

  # Swords 寶劍
  "Ace of Swords — 寶劍一",
  "Two of Swords — 寶劍二",
  "Three of Swords — 寶劍三",
  "Four of Swords — 寶劍四",
  "Five of Swords — 寶劍五",
  "Six of Swords — 寶劍六",
  "Seven of Swords — 寶劍七",
  "Eight of Swords — 寶劍八",
  "Nine of Swords — 寶劍九",
  "Ten of Swords — 寶劍十",
  "Page of Swords — 寶劍侍者",
  "Knight of Swords — 寶劍騎士",
  "Queen of Swords — 寶劍皇后",
  "King of Swords — 寶劍國王",

  # Pentacles 錢幣
  "Ace of Pentacles — 錢幣一",
  "Two of Pentacles — 錢幣二",
  "Three of Pentacles — 錢幣三",
  "Four of Pentacles — 錢幣四",
  "Five of Pentacles — 錢幣五",
  "Six of Pentacles — 錢幣六",
  "Seven of Pentacles — 錢幣七",
  "Eight of Pentacles — 錢幣八",
  "Nine of Pentacles — 錢幣九",
  "Ten of Pentacles — 錢幣十",
  "Page of Pentacles — 錢幣侍者",
  "Knight of Pentacles — 錢幣騎士",
  "Queen of Pentacles — 錢幣皇后",
  "King of Pentacles — 錢幣國王"
]